FROM mongo
MAINTAINER Diego Pinheiro diegompin@gmail.com



#VOLUME "${MHS_DATALINK}/mongo"
#ENTRYPOINT ["docker.sh"]

#RUN echo "RESTORING DATABASE "

#CMD mongorestore --username "root" --password "password" --gzip "/data/dump/" --verbose
#RUN echo "FINISHED RESTORING DATABASE"
#CMD mongoimport --host 172.16.0.1 --db test --collection users \
#   --type json --file /init.json --jsonArray
#COPY
#RUN mongoimport.sh
#ENTRYPOINT ["/entrypoint.sh"]
#requirements.txt /usr/local/airflow/mhs/requirements.txt

#USER root
#COPY requirements.txt /usr/local/airflow/mhs/requirements.txt
#ENV PYTHONPATH "${PYTHONPATH}:${AIRFLOW_HOME}"
#RUN ["pip", "install", "--user", "-r",  "mhs/requirements.txt"]
#USER airflow
#ENV PYTHONPATH /usr/local/airflow/mhs
#CMD ["python", "mhs/setup.py", "install", "--user"]
#COPY . /usr/local/airflow/mhs

#USER airflow

